[theme]
base="dark"
primaryColor="#20b8cd"

[server]
maxUploadSize = 500
enableCORS = false
enableXsrfProtection = false

[global]
showWarningOnDirectExecution = false

[browser]
gatherUsageStats = false

[client]
showFooter = false